# Generated by Django 3.2.8 on 2022-03-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addindiscussion',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('problem', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='remindersys',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('set_time', models.DateField()),
                ('tasks', models.TextField()),
                ('set_date', models.DateField()),
            ],
        ),
    ]
